name: run release package

on:
  schedule:
    - cron:  '1 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        ESA_TOKEN: ${{ secrets.ESA_TOKEN }}
        ESA_TEAMNAME: ${{ secrets.ESA_TEAMNAME }}
      run: cargo run