name: Rust

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build release
      run: cargo build --verbose --release
    - name: run
      run: ./target/release/esa-nikki