name: run release package

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build release
      run: cargo build --verbose --release
    - name: run
      env:
        SLACK_TOKEN: ${{ secret.SLACK_TOKEN }}
        ESA_TOKEN: ${{ secret.ESA_TOKEN }}
        ESA_TEAMNAME: ${{ secret.ESA_TEAMNAME }}
      run: ./target/release/esa-nikki